import orders from '../fixtures/orders.json'
import post from '../fixtures/post.json'

describe("Form", () => {
    beforeEach(() => {
        cy.intercept('http://localhost:3001/api/v1/orders/', orders)
        cy.intercept("POST", 'http://localhost:3001/api/v1/orders/4', post)
        cy.visit("http://localhost:3000/")

    })

    it('shoudl display data from the api', () => {
        cy.get('div')
        .get('.order')
        .get('h3')
        .should('contain', 'Pat')
        .get('ul')
        .get('li')
        .should('contain', 'beans')
        .get('li')
        .should('contain', 'lettuce')
        .get('li')
        .should('contain', 'carnitas')
        .get('li')
        .should('contain', 'queso fresco')
        cy.get('.order')
        .get('h3')
        .should('contain', 'Sam')
        .get('ul')
        .get('li')
        .should('contain', 'steak')
        .get('li')
        .should('contain', 'pico de gallo')
        .get('li')
        .should('contain', 'lettuce')
        .get('li')
        .should('contain', 'carnitas')
        .get('li')
        .should('contain', 'queso fresco')
        .get('li')
        .should('contain', 'jalapeno')
    })
    it('should be able to submit a post', () => {
        cy.get('input')
        .type('Maya')
        cy.get('button')
        .contains('beans')
        .click()
        cy.get('button')
        .contains('queso fresco')
        .click()
        cy.get('button')
        .contains('guacamole')
        .click()
        cy.get('button')
        .contains('lettuce')
        .click()
        cy.get('button')
        .contains('Submit Order')
        .click()
        cy.get('.order')
        .should('contain', 'Maya')
        cy.get('.order')
        .find('ul')
        .get('li')
        .should('contain', 'beans')
        .get('li')
        .should('contain', 'queso fresco')
        .get('li')
        .should('contain', 'guacamole')
        .get('li')
        .should('contain', 'lettuce')
})
})